# The required environment variables

# Choose the compilers and compilation flags according to the needs
CXX = g++
CXXFLAGS = -Wall -O2 -fPIC

# Any additional includes (-I/.../...)
ADDITIONAL_INC =

# Any additional linker flags (-L/.../... -l...)
ADDITIONAL_LDFLAGS =

###############################################################################
# TESTS

# Any additional includes (-I/.../...) for tests
# This project requires:
# CppUnit
ADDITIONAL_INC_TEST =

# Any additional linker flags (-L/.../... -l...) for tests
# This project requires:
# CppUnit (e.g. -lcppunit)
ADDITIONAL_LDFLAGS_TEST = -lcppunit
