function [nbp, dot_d3, dot_d3_intr] = import_MC_ttcoutput(filename,outputname)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,VARNAME2] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [VARNAME1,VARNAME2] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,VarName2] =
%   importfile('Run_cgDNAparamset2.1_nj_0_7394253485441907962_dot_d3',1,
%   220);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/03/08 09:45:34

%% Initialize variables.
delimiter = ' ';
startRow = 1;
endRow = inf;


%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen([ filename '/' outputname '_t0'] ,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
nbp = dataArray{:, 1};
dot_d3 = dataArray{:, 2};

%% Open the text file.
fileID = fopen([ filename '/' outputname '_t0_intr' ] ,'r');

%% Read columns of data according to format string.grid
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
nbp = dataArray{:, 1};
dot_d3_intr = dataArray{:, 2};


end

